export const refs = {
  hamburger: document.querySelector('[hamburger]'),
  body: document.querySelector('body'),
  modalNav: document.querySelector('#modal-nav'),
  btnOpen: document.querySelector('#btn-form-open'),
  btnClose: document.querySelector('#btn-form-close'),
  modalForm: document.querySelector('#modal-form'),
  carouselRow: document.querySelector('.customers__list'),
  carouselSlides: document.getElementsByClassName('customers__item'),
  btnPrev: document.querySelector('#btn-prev'),
  nextBtn: document.querySelector('#btn-next'),
  mobileLangBox: document.querySelector('#mobile-lang-box'),
  mobileLangList: document.querySelector('#mobile-lang-list'),
  mobileLangSvg: document.querySelector('.header__mobile-lang-svg'),
  langBox: document.querySelector('#langBox'),
  navLinksMobile: document.querySelectorAll('.header__mobile-nav-link'),
  navLinks: document.querySelectorAll('.header__nav-link'),
};
